name: CreativeArea
main: github.shor_van.creativearea.CreativeArea
version: 1.0.10b b28 (1.13.1)
api-version: 1.13
commands:
    tpcreative:
        description: Tps you to the creative area.
        usage: /tpcreative <player>
    leavecreative:
        description: Tps back to spawn.
        usage: /leavecreative